name: Publish

on:
  release:
    types: [ created ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 17.x
          cache: 'npm'
          scope: '@gh-stats'
          registry-url: 'https://registry.npmjs.org'
          
      - run: npm ci

      - name: Get latest tag and update version in package.json file
        run: npm version $(git tag | sort -r --version-sort | head -n1 | cut -c2-) -no-git-tag-version -f

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
